name: my_finance_flutter_3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.2.4
  dartx: ^1.1.0
  flutter_state_notifier: ^0.7.1
  focus_detector: ^2.0.1
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.0.1
  functional_listener: ^2.1.0
  logger: ^1.1.0
  modal_bottom_sheet: ^2.0.1
  provider: ^6.0.2
  responsive_builder: ^0.4.2
  rx_notifier: ^1.1.0
  rxdart: ^0.27.3
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  freezed: ^2.0.2
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
