import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class IconConstants {
  static const List<IconData> iconList = [
    FontAwesomeIcons.truckMedical,
    FontAwesomeIcons.babyCarriage,
    FontAwesomeIcons.scaleBalanced,
    FontAwesomeIcons.bed,
    FontAwesomeIcons.book,
    FontAwesomeIcons.car,
    FontAwesomeIcons.cashRegister,
    FontAwesomeIcons.chartLine,
    FontAwesomeIcons.chess,
    FontAwesomeIcons.houseChimneyMedical,
    FontAwesomeIcons.creditCard,
    FontAwesomeIcons.rightLeft,
    FontAwesomeIcons.fileInvoiceDollar,
    FontAwesomeIcons.futbol,
    FontAwesomeIcons.gamepad,
    FontAwesomeIcons.gasPump,
    FontAwesomeIcons.gift,
    FontAwesomeIcons.champagneGlasses,
    FontAwesomeIcons.graduationCap,
    FontAwesomeIcons.hammer,
    FontAwesomeIcons.handHoldingDollar,
    FontAwesomeIcons.heartPulse,
    FontAwesomeIcons.house,
    FontAwesomeIcons.houseLaptop,
    FontAwesomeIcons.leftLong,
    FontAwesomeIcons.rightLong,
    FontAwesomeIcons.moneyCheck,
    FontAwesomeIcons.paw,
    FontAwesomeIcons.piggyBank,
    FontAwesomeIcons.plane,
    FontAwesomeIcons.receipt,
    FontAwesomeIcons.basketShopping,
    FontAwesomeIcons.tablets,
    FontAwesomeIcons.ticketSimple,
    FontAwesomeIcons.toolbox,
    FontAwesomeIcons.screwdriverWrench,
    FontAwesomeIcons.train,
    FontAwesomeIcons.shirt,
    FontAwesomeIcons.user,
    FontAwesomeIcons.users,
    FontAwesomeIcons.utensils,
    FontAwesomeIcons.wallet,
  ];
}
