name: my_finance_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  database_domain:
    path: ../infra/database/domain
  navigation:
    path: ../infra/navigation

  auto_route: ^3.2.4
  dartx: ^1.1.0
  device_preview: ^1.0.0
  flutter_state_notifier: ^0.7.1
  focus_detector: ^2.0.1
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^1.1.0
  functional_listener: ^2.1.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  modal_bottom_sheet: ^2.0.1
  provider: ^6.0.2
  responsive_builder: ^0.4.2
  rx_notifier: ^1.1.0
  rxdart: ^0.27.3
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
