name: my_finance_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  theme:
    path: ../theme
  database_domain:
    path: ../infra/database/domain
  navigation:
    path: ../infra/navigation

  auto_route: ^5.0.1
  dartx: ^1.1.0
  device_preview: ^1.1.0
  flutter_state_notifier: ^0.7.1
  focus_detector: ^2.0.1
  font_awesome_flutter: ^10.2.1
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.1.0
  functional_listener: ^2.1.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  modal_bottom_sheet: ^2.1.2
  provider: ^6.0.3
  responsive_builder: ^0.4.3
  rx_notifier: ^1.1.0
  rxdart: ^0.27.5
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  freezed: ^2.1.0
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
