import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class IconConstants {
  static const List<IconData> iconList = [
    FontAwesomeIcons.ambulance,
    FontAwesomeIcons.babyCarriage,
    FontAwesomeIcons.balanceScale,
    FontAwesomeIcons.bed,
    FontAwesomeIcons.book,
    FontAwesomeIcons.car,
    FontAwesomeIcons.cashRegister,
    FontAwesomeIcons.chartLine,
    FontAwesomeIcons.chess,
    FontAwesomeIcons.clinicMedical,
    FontAwesomeIcons.creditCard,
    FontAwesomeIcons.exchangeAlt,
    FontAwesomeIcons.fileInvoiceDollar,
    FontAwesomeIcons.futbol,
    FontAwesomeIcons.gamepad,
    FontAwesomeIcons.gasPump,
    FontAwesomeIcons.gift,
    FontAwesomeIcons.glassCheers,
    FontAwesomeIcons.graduationCap,
    FontAwesomeIcons.hammer,
    FontAwesomeIcons.handHoldingUsd,
    FontAwesomeIcons.heartbeat,
    FontAwesomeIcons.home,
    FontAwesomeIcons.laptopHouse,
    FontAwesomeIcons.longArrowAltLeft,
    FontAwesomeIcons.longArrowAltRight,
    FontAwesomeIcons.moneyCheck,
    FontAwesomeIcons.paw,
    FontAwesomeIcons.piggyBank,
    FontAwesomeIcons.plane,
    FontAwesomeIcons.receipt,
    FontAwesomeIcons.shoppingBasket,
    FontAwesomeIcons.tablets,
    FontAwesomeIcons.ticketAlt,
    FontAwesomeIcons.toolbox,
    FontAwesomeIcons.tools,
    FontAwesomeIcons.train,
    FontAwesomeIcons.tshirt,
    FontAwesomeIcons.user,
    FontAwesomeIcons.users,
    FontAwesomeIcons.utensils,
    FontAwesomeIcons.wallet,
  ];
}
