name: navigation
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.0.1
  modal_bottom_sheet: ^2.0.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0

flutter:
